#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Com
  module Guardium
    module Proto
      module Datasource
        # forward declarations
        class Timestamp < ::ProtocolBuffers::Message; end
        class Handshake < ::ProtocolBuffers::Message; end
        class ForwardingConfiguration < ::ProtocolBuffers::Message; end
        class Ping < ::ProtocolBuffers::Message; end
        class GuardDsMessage < ::ProtocolBuffers::Message; end
        class SessionStart < ::ProtocolBuffers::Message; end
        class SessionLocator < ::ProtocolBuffers::Message; end
        class ApplicationData < ::ProtocolBuffers::Message; end
        class Accessor < ::ProtocolBuffers::Message; end
        class GDMConstruct < ::ProtocolBuffers::Message; end
        class GDMSentence < ::ProtocolBuffers::Message; end
        class GDMObject < ::ProtocolBuffers::Message; end
        class GDMField < ::ProtocolBuffers::Message; end
        class PositionalString < ::ProtocolBuffers::Message; end
        class ClientRequest < ::ProtocolBuffers::Message; end
        class BindInfo < ::ProtocolBuffers::Message; end
        class BindVariable < ::ProtocolBuffers::Message; end

        class Timestamp < ::ProtocolBuffers::Message
          required :fixed32, :unix_time, 1
          optional :fixed32, :usec, 2
          optional :sfixed32, :tz_min, 3
          optional :sfixed32, :tz_dst, 4

          gen_methods! # new fields ignored after this point
        end

        class Handshake < ::ProtocolBuffers::Message
          required ::Com::Guardium::Proto::Datasource::Timestamp, :timestamp, 1
          required :string, :client_identifier, 2
          required :string, :current_master, 3
          required :fixed32, :current_master_ip, 4
          optional :string, :vendor, 5
          optional :string, :product, 6
          optional :string, :version, 7
          optional :bool, :firewall, 8
          optional :bool, :transient, 9
          repeated ::Com::Guardium::Proto::Datasource::ForwardingConfiguration, :forwarding, 10
          optional :bool, :sink, 11, :default => false
          optional :bool, :policy_push, 12

          gen_methods! # new fields ignored after this point
        end

        class ForwardingConfiguration < ::ProtocolBuffers::Message
          optional :fixed32, :vendor_id, 1
          repeated :string, :forward_messages, 2
          repeated :string, :filter_messages, 3

          gen_methods! # new fields ignored after this point
        end

        class Ping < ::ProtocolBuffers::Message
          required ::Com::Guardium::Proto::Datasource::Timestamp, :timestamp, 1
          required :string, :client_identifier, 2
          required :string, :current_master, 3
          required :fixed32, :current_master_ip, 4

          gen_methods! # new fields ignored after this point
        end

        class GuardDsMessage < ::ProtocolBuffers::Message
          # forward declarations

          # enums
          module Type
            include ::ProtocolBuffers::Enum
            HANDSHAKE = 1
            PING = 2
            ERROR_MSG = 3
            SESSION_START = 4
            SESSION_END = 5
            CLIENT_REQUEST = 6
            SERVER_REPLY = 7
            POLICY_RULES = 8
            SESSION_DATA = 9
            MONITOR_SESSION = 10
            EXCEPTION = 11
            ICAP = 12
            CONFIG = 13
            PARSE = 14
            COLLECTOR_FEATURE = 15
            SYSTEM_I_RAW = 16
            GDM_APP_DATA = 17
            QUERYREWRITE_PREVIEW = 18
          end

          required ::Com::Guardium::Proto::Datasource::GuardDsMessage::Type, :type, 1
          optional ::Com::Guardium::Proto::Datasource::Handshake, :handshake, 2
          optional ::Com::Guardium::Proto::Datasource::Ping, :ping, 3
          optional ::Com::Guardium::Proto::Datasource::SessionStart, :session_start, 4
          optional ::Com::Guardium::Proto::Datasource::ClientRequest, :client_request, 6

          gen_methods! # new fields ignored after this point
        end

        class SessionStart < ::ProtocolBuffers::Message
          optional :int64, :session_id, 1
          optional ::Com::Guardium::Proto::Datasource::SessionLocator, :session_locator, 2
          optional ::Com::Guardium::Proto::Datasource::Timestamp, :timestamp, 3
          optional ::Com::Guardium::Proto::Datasource::Accessor, :accessor, 4
          optional :string, :uid_chain, 5
          optional :int64, :prev_session_id, 6
          optional :string, :process_id, 7
          optional :string, :terminal_id, 8
          optional :string, :db_name, 9
          optional :string, :app_user_name, 10

          gen_methods! # new fields ignored after this point
        end

        class SessionLocator < ::ProtocolBuffers::Message
          optional :fixed32, :client_ip, 1
          optional :fixed32, :client_port, 2
          optional :fixed32, :server_ip, 3
          optional :fixed32, :server_port, 4

          gen_methods! # new fields ignored after this point
        end

        class ApplicationData < ::ProtocolBuffers::Message
          # forward declarations

          # enums
          module DataType
            include ::ProtocolBuffers::Enum
            TEXT = 1
            RAW = 2
            CONSTRUCT = 3
          end

          module LanguageType
            include ::ProtocolBuffers::Enum
            FREE_TEXT = 4
            MSSQL = 8
            SYB = 16
            ORACLE = 32
            DB2 = 64
            INFX = 1024
            MYSQL = 8192
            MSSP = 4194304
            OPTIM_AUDIT = 8388608
            OPTIM_REDACT = 2048
            BIG_INSIGHTS = 16777216
          end

          optional ::Com::Guardium::Proto::Datasource::ApplicationData::LanguageType, :language, 1
          required ::Com::Guardium::Proto::Datasource::ApplicationData::DataType, :type, 2
          optional :string, :text, 3
          optional :bytes, :packet, 4
          optional ::Com::Guardium::Proto::Datasource::GDMConstruct, :construct, 5
          required ::Com::Guardium::Proto::Datasource::Timestamp, :timestamp, 6
          optional :string, :application_user, 7
          optional ::Com::Guardium::Proto::Datasource::SessionLocator, :session_locator, 8
          optional :string, :variables_values, 9

          gen_methods! # new fields ignored after this point
        end

        class Accessor < ::ProtocolBuffers::Message
          required :string, :db_user, 1
          required :string, :server_type, 2
          optional :string, :server_os, 3
          optional :string, :client_os, 4
          optional :string, :client_hostname, 5
          optional :string, :server_hostname, 6
          optional :string, :comm_protocol, 7
          optional :string, :db_protocol, 8
          optional :string, :db_protocol_version, 9
          optional :string, :os_user, 10
          optional :string, :source_program, 11
          optional :string, :client_mac, 12
          optional :string, :server_description, 13
          optional :string, :service_name, 14
          optional ::Com::Guardium::Proto::Datasource::ApplicationData::LanguageType, :language, 15
          optional ::Com::Guardium::Proto::Datasource::ApplicationData::DataType, :type, 16, :default => ::Com::Guardium::Proto::Datasource::ApplicationData::DataType::TEXT

          gen_methods! # new fields ignored after this point
        end

        class GDMConstruct < ::ProtocolBuffers::Message
          repeated ::Com::Guardium::Proto::Datasource::GDMSentence, :sentences, 1
          optional :string, :original_sql, 2
          optional :string, :full_sql, 3
          optional :bool, :is_valid, 4, :default => true
          optional :int32, :statement_type, 5

          gen_methods! # new fields ignored after this point
        end

        class GDMSentence < ::ProtocolBuffers::Message
          required :string, :verb, 1
          repeated ::Com::Guardium::Proto::Datasource::GDMSentence, :descendants, 2
          repeated ::Com::Guardium::Proto::Datasource::GDMObject, :objects, 3
          repeated ::Com::Guardium::Proto::Datasource::GDMField, :sentence_fields, 4
          optional ::Com::Guardium::Proto::Datasource::PositionalString, :position, 5

          gen_methods! # new fields ignored after this point
        end

        class GDMObject < ::ProtocolBuffers::Message
          required :string, :name, 1
          optional :string, :schema, 2
          optional :string, :type, 3
          repeated ::Com::Guardium::Proto::Datasource::GDMField, :object_fields, 4
          optional ::Com::Guardium::Proto::Datasource::PositionalString, :position, 5

          gen_methods! # new fields ignored after this point
        end

        class GDMField < ::ProtocolBuffers::Message
          # forward declarations

          # enums
          module Origin
            include ::ProtocolBuffers::Enum
            CLAUSE_WHERE = 1
            CLAUSE_ORDER_BY = 2
            CLAUSE_HAVING = 3
            CLAUSE_GROUP_BY = 4
            CLAUSE_LIST = 5
            CLAUSE_ON = 6
          end

          required :string, :name, 1
          repeated ::Com::Guardium::Proto::Datasource::GDMField::Origin, :origins, 2
          optional :bytes, :value, 3
          optional ::Com::Guardium::Proto::Datasource::PositionalString, :position, 4

          gen_methods! # new fields ignored after this point
        end

        class PositionalString < ::ProtocolBuffers::Message
          optional :uint32, :start, 1
          optional :uint32, :end, 2

          gen_methods! # new fields ignored after this point
        end

        class ClientRequest < ::ProtocolBuffers::Message
          required :int64, :session_id, 1
          optional :int64, :request_id, 2
          required ::Com::Guardium::Proto::Datasource::ApplicationData, :data, 3
          optional ::Com::Guardium::Proto::Datasource::BindInfo, :bind_info, 4

          gen_methods! # new fields ignored after this point
        end

        class BindInfo < ::ProtocolBuffers::Message
          repeated ::Com::Guardium::Proto::Datasource::BindVariable, :vars, 1

          gen_methods! # new fields ignored after this point
        end

        class BindVariable < ::ProtocolBuffers::Message
          optional :int32, :type, 1
          optional :string, :value, 2

          gen_methods! # new fields ignored after this point
        end

      end
    end
  end
end
